/**
 * R2 client for interacting with Cloudflare R2 object storage.
 * Uses native R2 bindings available through Cloudflare Workers runtime.
 *
 * Note: All types (R2Bucket, R2ObjectBody, etc.) are available from
 * workers/worker-configuration.d.ts (auto-generated by `wrangler types`).
 */

/**
 * Uploads a file to R2 storage.
 * @param bucket - The R2Bucket binding from Cloudflare Workers env
 * @param key - The R2 object key (path/filename)
 * @param file - File content as ArrayBuffer or ReadableStream
 * @param contentType - The MIME type of the file
 */
export async function uploadFile(
	bucket: R2Bucket,
	key: string,
	file: ArrayBuffer | ReadableStream,
	contentType: string,
): Promise<void> {
	await bucket.put(key, file, {
		httpMetadata: { contentType },
	});
}

/**
 * Downloads a file from R2 storage.
 * @param bucket - The R2Bucket binding from Cloudflare Workers env
 * @param key - The R2 object key (path/filename)
 * @returns R2ObjectBody if found, null if not found
 */
export async function downloadFile(
	bucket: R2Bucket,
	key: string,
): Promise<R2ObjectBody | null> {
	return await bucket.get(key);
}

/**
 * Fetches file content from R2 as a Buffer.
 * Used for text extraction after upload confirmation.
 * @param bucket - The R2Bucket binding from Cloudflare Workers env
 * @param key - The R2 object key
 * @returns File content as Buffer, or null if fetch fails
 */
export async function fetchFileContent(
	bucket: R2Bucket,
	key: string,
): Promise<Buffer | null> {
	try {
		const object = await bucket.get(key);

		if (!object) {
			console.error("R2 object not found for key:", key);
			return null;
		}

		// Convert R2ObjectBody to Buffer
		const arrayBuffer = await object.arrayBuffer();
		return Buffer.from(arrayBuffer);
	} catch (error) {
		console.error("Failed to fetch file from R2:", error);
		return null;
	}
}

/**
 * Deletes an object from R2 storage.
 * @param bucket - The R2Bucket binding from Cloudflare Workers env
 * @param key - The R2 object key to delete
 */
export async function deleteObject(
	bucket: R2Bucket,
	key: string,
): Promise<void> {
	await bucket.delete(key);
}
