/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingCreateOrgRouteImport } from './routes/onboarding/create-org'
import { Route as AuthedOrgsRouteImport } from './routes/_authed/orgs'
import { Route as AuthedOrgSlugRouteImport } from './routes/_authed/org/$slug'
import { Route as AuthedOrgSlugSourcesRouteImport } from './routes/_authed/org/$slug/sources'
import { Route as AuthedOrgSlugDashboardRouteImport } from './routes/_authed/org/$slug/dashboard'
import { Route as AuthedOrgSlugSettingsIndexRouteImport } from './routes/_authed/org/$slug/settings/index'
import { Route as AuthedOrgSlugInboxIndexRouteImport } from './routes/_authed/org/$slug/inbox/index'
import { Route as AuthedOrgSlugDraftsIndexRouteImport } from './routes/_authed/org/$slug/drafts/index'
import { Route as AuthedOrgSlugSourcesSourceIdRouteImport } from './routes/_authed/org/$slug/sources/$sourceId'
import { Route as AuthedOrgSlugSettingsMembersRouteImport } from './routes/_authed/org/$slug/settings/members'
import { Route as AuthedOrgSlugSettingsGhostWriterRouteImport } from './routes/_authed/org/$slug/settings/ghost-writer'
import { Route as AuthedOrgSlugSettingsAutoDraftRouteImport } from './routes/_authed/org/$slug/settings/auto-draft'
import { Route as AuthedOrgSlugInboxAddUrlRouteImport } from './routes/_authed/org/$slug/inbox/add-url'
import { Route as AuthedOrgSlugInboxEntryIdRouteImport } from './routes/_authed/org/$slug/inbox/$entryId'
import { Route as AuthedOrgSlugDraftsDraftIdRouteImport } from './routes/_authed/org/$slug/drafts/$draftId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCreateOrgRoute = OnboardingCreateOrgRouteImport.update({
  id: '/onboarding/create-org',
  path: '/onboarding/create-org',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOrgsRoute = AuthedOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgSlugRoute = AuthedOrgSlugRouteImport.update({
  id: '/org/$slug',
  path: '/org/$slug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgSlugSourcesRoute = AuthedOrgSlugSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthedOrgSlugRoute,
} as any)
const AuthedOrgSlugDashboardRoute = AuthedOrgSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedOrgSlugRoute,
} as any)
const AuthedOrgSlugSettingsIndexRoute =
  AuthedOrgSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthedOrgSlugRoute,
  } as any)
const AuthedOrgSlugInboxIndexRoute = AuthedOrgSlugInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AuthedOrgSlugRoute,
} as any)
const AuthedOrgSlugDraftsIndexRoute =
  AuthedOrgSlugDraftsIndexRouteImport.update({
    id: '/drafts/',
    path: '/drafts/',
    getParentRoute: () => AuthedOrgSlugRoute,
  } as any)
const AuthedOrgSlugSourcesSourceIdRoute =
  AuthedOrgSlugSourcesSourceIdRouteImport.update({
    id: '/$sourceId',
    path: '/$sourceId',
    getParentRoute: () => AuthedOrgSlugSourcesRoute,
  } as any)
const AuthedOrgSlugSettingsMembersRoute =
  AuthedOrgSlugSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AuthedOrgSlugRoute,
  } as any)
const AuthedOrgSlugSettingsGhostWriterRoute =
  AuthedOrgSlugSettingsGhostWriterRouteImport.update({
    id: '/settings/ghost-writer',
    path: '/settings/ghost-writer',
    getParentRoute: () => AuthedOrgSlugRoute,
  } as any)
const AuthedOrgSlugSettingsAutoDraftRoute =
  AuthedOrgSlugSettingsAutoDraftRouteImport.update({
    id: '/settings/auto-draft',
    path: '/settings/auto-draft',
    getParentRoute: () => AuthedOrgSlugRoute,
  } as any)
const AuthedOrgSlugInboxAddUrlRoute =
  AuthedOrgSlugInboxAddUrlRouteImport.update({
    id: '/inbox/add-url',
    path: '/inbox/add-url',
    getParentRoute: () => AuthedOrgSlugRoute,
  } as any)
const AuthedOrgSlugInboxEntryIdRoute =
  AuthedOrgSlugInboxEntryIdRouteImport.update({
    id: '/inbox/$entryId',
    path: '/inbox/$entryId',
    getParentRoute: () => AuthedOrgSlugRoute,
  } as any)
const AuthedOrgSlugDraftsDraftIdRoute =
  AuthedOrgSlugDraftsDraftIdRouteImport.update({
    id: '/drafts/$draftId',
    path: '/drafts/$draftId',
    getParentRoute: () => AuthedOrgSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/orgs': typeof AuthedOrgsRoute
  '/onboarding/create-org': typeof OnboardingCreateOrgRoute
  '/org/$slug': typeof AuthedOrgSlugRouteWithChildren
  '/org/$slug/dashboard': typeof AuthedOrgSlugDashboardRoute
  '/org/$slug/sources': typeof AuthedOrgSlugSourcesRouteWithChildren
  '/org/$slug/drafts/$draftId': typeof AuthedOrgSlugDraftsDraftIdRoute
  '/org/$slug/inbox/$entryId': typeof AuthedOrgSlugInboxEntryIdRoute
  '/org/$slug/inbox/add-url': typeof AuthedOrgSlugInboxAddUrlRoute
  '/org/$slug/settings/auto-draft': typeof AuthedOrgSlugSettingsAutoDraftRoute
  '/org/$slug/settings/ghost-writer': typeof AuthedOrgSlugSettingsGhostWriterRoute
  '/org/$slug/settings/members': typeof AuthedOrgSlugSettingsMembersRoute
  '/org/$slug/sources/$sourceId': typeof AuthedOrgSlugSourcesSourceIdRoute
  '/org/$slug/drafts': typeof AuthedOrgSlugDraftsIndexRoute
  '/org/$slug/inbox': typeof AuthedOrgSlugInboxIndexRoute
  '/org/$slug/settings': typeof AuthedOrgSlugSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/orgs': typeof AuthedOrgsRoute
  '/onboarding/create-org': typeof OnboardingCreateOrgRoute
  '/org/$slug': typeof AuthedOrgSlugRouteWithChildren
  '/org/$slug/dashboard': typeof AuthedOrgSlugDashboardRoute
  '/org/$slug/sources': typeof AuthedOrgSlugSourcesRouteWithChildren
  '/org/$slug/drafts/$draftId': typeof AuthedOrgSlugDraftsDraftIdRoute
  '/org/$slug/inbox/$entryId': typeof AuthedOrgSlugInboxEntryIdRoute
  '/org/$slug/inbox/add-url': typeof AuthedOrgSlugInboxAddUrlRoute
  '/org/$slug/settings/auto-draft': typeof AuthedOrgSlugSettingsAutoDraftRoute
  '/org/$slug/settings/ghost-writer': typeof AuthedOrgSlugSettingsGhostWriterRoute
  '/org/$slug/settings/members': typeof AuthedOrgSlugSettingsMembersRoute
  '/org/$slug/sources/$sourceId': typeof AuthedOrgSlugSourcesSourceIdRoute
  '/org/$slug/drafts': typeof AuthedOrgSlugDraftsIndexRoute
  '/org/$slug/inbox': typeof AuthedOrgSlugInboxIndexRoute
  '/org/$slug/settings': typeof AuthedOrgSlugSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/orgs': typeof AuthedOrgsRoute
  '/onboarding/create-org': typeof OnboardingCreateOrgRoute
  '/_authed/org/$slug': typeof AuthedOrgSlugRouteWithChildren
  '/_authed/org/$slug/dashboard': typeof AuthedOrgSlugDashboardRoute
  '/_authed/org/$slug/sources': typeof AuthedOrgSlugSourcesRouteWithChildren
  '/_authed/org/$slug/drafts/$draftId': typeof AuthedOrgSlugDraftsDraftIdRoute
  '/_authed/org/$slug/inbox/$entryId': typeof AuthedOrgSlugInboxEntryIdRoute
  '/_authed/org/$slug/inbox/add-url': typeof AuthedOrgSlugInboxAddUrlRoute
  '/_authed/org/$slug/settings/auto-draft': typeof AuthedOrgSlugSettingsAutoDraftRoute
  '/_authed/org/$slug/settings/ghost-writer': typeof AuthedOrgSlugSettingsGhostWriterRoute
  '/_authed/org/$slug/settings/members': typeof AuthedOrgSlugSettingsMembersRoute
  '/_authed/org/$slug/sources/$sourceId': typeof AuthedOrgSlugSourcesSourceIdRoute
  '/_authed/org/$slug/drafts/': typeof AuthedOrgSlugDraftsIndexRoute
  '/_authed/org/$slug/inbox/': typeof AuthedOrgSlugInboxIndexRoute
  '/_authed/org/$slug/settings/': typeof AuthedOrgSlugSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/orgs'
    | '/onboarding/create-org'
    | '/org/$slug'
    | '/org/$slug/dashboard'
    | '/org/$slug/sources'
    | '/org/$slug/drafts/$draftId'
    | '/org/$slug/inbox/$entryId'
    | '/org/$slug/inbox/add-url'
    | '/org/$slug/settings/auto-draft'
    | '/org/$slug/settings/ghost-writer'
    | '/org/$slug/settings/members'
    | '/org/$slug/sources/$sourceId'
    | '/org/$slug/drafts'
    | '/org/$slug/inbox'
    | '/org/$slug/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/orgs'
    | '/onboarding/create-org'
    | '/org/$slug'
    | '/org/$slug/dashboard'
    | '/org/$slug/sources'
    | '/org/$slug/drafts/$draftId'
    | '/org/$slug/inbox/$entryId'
    | '/org/$slug/inbox/add-url'
    | '/org/$slug/settings/auto-draft'
    | '/org/$slug/settings/ghost-writer'
    | '/org/$slug/settings/members'
    | '/org/$slug/sources/$sourceId'
    | '/org/$slug/drafts'
    | '/org/$slug/inbox'
    | '/org/$slug/settings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/orgs'
    | '/onboarding/create-org'
    | '/_authed/org/$slug'
    | '/_authed/org/$slug/dashboard'
    | '/_authed/org/$slug/sources'
    | '/_authed/org/$slug/drafts/$draftId'
    | '/_authed/org/$slug/inbox/$entryId'
    | '/_authed/org/$slug/inbox/add-url'
    | '/_authed/org/$slug/settings/auto-draft'
    | '/_authed/org/$slug/settings/ghost-writer'
    | '/_authed/org/$slug/settings/members'
    | '/_authed/org/$slug/sources/$sourceId'
    | '/_authed/org/$slug/drafts/'
    | '/_authed/org/$slug/inbox/'
    | '/_authed/org/$slug/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  OnboardingCreateOrgRoute: typeof OnboardingCreateOrgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/create-org': {
      id: '/onboarding/create-org'
      path: '/onboarding/create-org'
      fullPath: '/onboarding/create-org'
      preLoaderRoute: typeof OnboardingCreateOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/orgs': {
      id: '/_authed/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof AuthedOrgsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/$slug': {
      id: '/_authed/org/$slug'
      path: '/org/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof AuthedOrgSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/$slug/sources': {
      id: '/_authed/org/$slug/sources'
      path: '/sources'
      fullPath: '/org/$slug/sources'
      preLoaderRoute: typeof AuthedOrgSlugSourcesRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/org/$slug/dashboard': {
      id: '/_authed/org/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/org/$slug/dashboard'
      preLoaderRoute: typeof AuthedOrgSlugDashboardRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/org/$slug/settings/': {
      id: '/_authed/org/$slug/settings/'
      path: '/settings'
      fullPath: '/org/$slug/settings'
      preLoaderRoute: typeof AuthedOrgSlugSettingsIndexRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/org/$slug/inbox/': {
      id: '/_authed/org/$slug/inbox/'
      path: '/inbox'
      fullPath: '/org/$slug/inbox'
      preLoaderRoute: typeof AuthedOrgSlugInboxIndexRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/org/$slug/drafts/': {
      id: '/_authed/org/$slug/drafts/'
      path: '/drafts'
      fullPath: '/org/$slug/drafts'
      preLoaderRoute: typeof AuthedOrgSlugDraftsIndexRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/org/$slug/sources/$sourceId': {
      id: '/_authed/org/$slug/sources/$sourceId'
      path: '/$sourceId'
      fullPath: '/org/$slug/sources/$sourceId'
      preLoaderRoute: typeof AuthedOrgSlugSourcesSourceIdRouteImport
      parentRoute: typeof AuthedOrgSlugSourcesRoute
    }
    '/_authed/org/$slug/settings/members': {
      id: '/_authed/org/$slug/settings/members'
      path: '/settings/members'
      fullPath: '/org/$slug/settings/members'
      preLoaderRoute: typeof AuthedOrgSlugSettingsMembersRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/org/$slug/settings/ghost-writer': {
      id: '/_authed/org/$slug/settings/ghost-writer'
      path: '/settings/ghost-writer'
      fullPath: '/org/$slug/settings/ghost-writer'
      preLoaderRoute: typeof AuthedOrgSlugSettingsGhostWriterRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/org/$slug/settings/auto-draft': {
      id: '/_authed/org/$slug/settings/auto-draft'
      path: '/settings/auto-draft'
      fullPath: '/org/$slug/settings/auto-draft'
      preLoaderRoute: typeof AuthedOrgSlugSettingsAutoDraftRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/org/$slug/inbox/add-url': {
      id: '/_authed/org/$slug/inbox/add-url'
      path: '/inbox/add-url'
      fullPath: '/org/$slug/inbox/add-url'
      preLoaderRoute: typeof AuthedOrgSlugInboxAddUrlRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/org/$slug/inbox/$entryId': {
      id: '/_authed/org/$slug/inbox/$entryId'
      path: '/inbox/$entryId'
      fullPath: '/org/$slug/inbox/$entryId'
      preLoaderRoute: typeof AuthedOrgSlugInboxEntryIdRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/org/$slug/drafts/$draftId': {
      id: '/_authed/org/$slug/drafts/$draftId'
      path: '/drafts/$draftId'
      fullPath: '/org/$slug/drafts/$draftId'
      preLoaderRoute: typeof AuthedOrgSlugDraftsDraftIdRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
  }
}

interface AuthedOrgSlugSourcesRouteChildren {
  AuthedOrgSlugSourcesSourceIdRoute: typeof AuthedOrgSlugSourcesSourceIdRoute
}

const AuthedOrgSlugSourcesRouteChildren: AuthedOrgSlugSourcesRouteChildren = {
  AuthedOrgSlugSourcesSourceIdRoute: AuthedOrgSlugSourcesSourceIdRoute,
}

const AuthedOrgSlugSourcesRouteWithChildren =
  AuthedOrgSlugSourcesRoute._addFileChildren(AuthedOrgSlugSourcesRouteChildren)

interface AuthedOrgSlugRouteChildren {
  AuthedOrgSlugDashboardRoute: typeof AuthedOrgSlugDashboardRoute
  AuthedOrgSlugSourcesRoute: typeof AuthedOrgSlugSourcesRouteWithChildren
  AuthedOrgSlugDraftsDraftIdRoute: typeof AuthedOrgSlugDraftsDraftIdRoute
  AuthedOrgSlugInboxEntryIdRoute: typeof AuthedOrgSlugInboxEntryIdRoute
  AuthedOrgSlugInboxAddUrlRoute: typeof AuthedOrgSlugInboxAddUrlRoute
  AuthedOrgSlugSettingsAutoDraftRoute: typeof AuthedOrgSlugSettingsAutoDraftRoute
  AuthedOrgSlugSettingsGhostWriterRoute: typeof AuthedOrgSlugSettingsGhostWriterRoute
  AuthedOrgSlugSettingsMembersRoute: typeof AuthedOrgSlugSettingsMembersRoute
  AuthedOrgSlugDraftsIndexRoute: typeof AuthedOrgSlugDraftsIndexRoute
  AuthedOrgSlugInboxIndexRoute: typeof AuthedOrgSlugInboxIndexRoute
  AuthedOrgSlugSettingsIndexRoute: typeof AuthedOrgSlugSettingsIndexRoute
}

const AuthedOrgSlugRouteChildren: AuthedOrgSlugRouteChildren = {
  AuthedOrgSlugDashboardRoute: AuthedOrgSlugDashboardRoute,
  AuthedOrgSlugSourcesRoute: AuthedOrgSlugSourcesRouteWithChildren,
  AuthedOrgSlugDraftsDraftIdRoute: AuthedOrgSlugDraftsDraftIdRoute,
  AuthedOrgSlugInboxEntryIdRoute: AuthedOrgSlugInboxEntryIdRoute,
  AuthedOrgSlugInboxAddUrlRoute: AuthedOrgSlugInboxAddUrlRoute,
  AuthedOrgSlugSettingsAutoDraftRoute: AuthedOrgSlugSettingsAutoDraftRoute,
  AuthedOrgSlugSettingsGhostWriterRoute: AuthedOrgSlugSettingsGhostWriterRoute,
  AuthedOrgSlugSettingsMembersRoute: AuthedOrgSlugSettingsMembersRoute,
  AuthedOrgSlugDraftsIndexRoute: AuthedOrgSlugDraftsIndexRoute,
  AuthedOrgSlugInboxIndexRoute: AuthedOrgSlugInboxIndexRoute,
  AuthedOrgSlugSettingsIndexRoute: AuthedOrgSlugSettingsIndexRoute,
}

const AuthedOrgSlugRouteWithChildren = AuthedOrgSlugRoute._addFileChildren(
  AuthedOrgSlugRouteChildren,
)

interface AuthedRouteChildren {
  AuthedOrgsRoute: typeof AuthedOrgsRoute
  AuthedOrgSlugRoute: typeof AuthedOrgSlugRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOrgsRoute: AuthedOrgsRoute,
  AuthedOrgSlugRoute: AuthedOrgSlugRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  OnboardingCreateOrgRoute: OnboardingCreateOrgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
