/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AuthedProjectsProjectIdRouteImport } from './routes/_authed/projects.$projectId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as AuthedProjectsProjectIdIndexRouteImport } from './routes/_authed/projects.$projectId.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as AuthedProjectsProjectIdSettingsRouteImport } from './routes/_authed/projects.$projectId.settings'
import { Route as AuthedProjectsProjectIdPersonasRouteImport } from './routes/_authed/projects.$projectId.personas'
import { Route as AuthedProjectsProjectIdKnowledgeBaseRouteImport } from './routes/_authed/projects.$projectId.knowledge-base'
import { Route as AuthedProjectsProjectIdExamplesRouteImport } from './routes/_authed/projects.$projectId.examples'
import { Route as AuthedProjectsProjectIdCategoriesRouteImport } from './routes/_authed/projects.$projectId.categories'
import { Route as AuthedProjectsProjectIdBrandVoicesRouteImport } from './routes/_authed/projects.$projectId.brand-voices'
import { Route as AuthedProjectsProjectIdContentIndexRouteImport } from './routes/_authed/projects.$projectId/content.index'
import { Route as AuthedProjectsProjectIdContentNewRouteImport } from './routes/_authed/projects.$projectId/content.new'
import { Route as AuthedProjectsProjectIdContentContentIdRouteImport } from './routes/_authed/projects.$projectId/content.$contentId'
import { Route as AuthedProjectsProjectIdContentContentIdVersionsRouteImport } from './routes/_authed/projects.$projectId/content.$contentId.versions'
import { Route as AuthedProjectsProjectIdContentContentIdImagesRouteImport } from './routes/_authed/projects.$projectId/content.$contentId.images'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProjectsProjectIdRoute = AuthedProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AuthedRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProjectsProjectIdIndexRoute =
  AuthedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProjectsProjectIdSettingsRoute =
  AuthedProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdPersonasRoute =
  AuthedProjectsProjectIdPersonasRouteImport.update({
    id: '/personas',
    path: '/personas',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdKnowledgeBaseRoute =
  AuthedProjectsProjectIdKnowledgeBaseRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdExamplesRoute =
  AuthedProjectsProjectIdExamplesRouteImport.update({
    id: '/examples',
    path: '/examples',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdCategoriesRoute =
  AuthedProjectsProjectIdCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdBrandVoicesRoute =
  AuthedProjectsProjectIdBrandVoicesRouteImport.update({
    id: '/brand-voices',
    path: '/brand-voices',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdContentIndexRoute =
  AuthedProjectsProjectIdContentIndexRouteImport.update({
    id: '/content/',
    path: '/content/',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdContentNewRoute =
  AuthedProjectsProjectIdContentNewRouteImport.update({
    id: '/content/new',
    path: '/content/new',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdContentContentIdRoute =
  AuthedProjectsProjectIdContentContentIdRouteImport.update({
    id: '/content/$contentId',
    path: '/content/$contentId',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdContentContentIdVersionsRoute =
  AuthedProjectsProjectIdContentContentIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => AuthedProjectsProjectIdContentContentIdRoute,
  } as any)
const AuthedProjectsProjectIdContentContentIdImagesRoute =
  AuthedProjectsProjectIdContentContentIdImagesRouteImport.update({
    id: '/images',
    path: '/images',
    getParentRoute: () => AuthedProjectsProjectIdContentContentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/profile': typeof AuthedProfileRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/projects/$projectId/brand-voices': typeof AuthedProjectsProjectIdBrandVoicesRoute
  '/projects/$projectId/categories': typeof AuthedProjectsProjectIdCategoriesRoute
  '/projects/$projectId/examples': typeof AuthedProjectsProjectIdExamplesRoute
  '/projects/$projectId/knowledge-base': typeof AuthedProjectsProjectIdKnowledgeBaseRoute
  '/projects/$projectId/personas': typeof AuthedProjectsProjectIdPersonasRoute
  '/projects/$projectId/settings': typeof AuthedProjectsProjectIdSettingsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/projects/$projectId/content/$contentId': typeof AuthedProjectsProjectIdContentContentIdRouteWithChildren
  '/projects/$projectId/content/new': typeof AuthedProjectsProjectIdContentNewRoute
  '/projects/$projectId/content': typeof AuthedProjectsProjectIdContentIndexRoute
  '/projects/$projectId/content/$contentId/images': typeof AuthedProjectsProjectIdContentContentIdImagesRoute
  '/projects/$projectId/content/$contentId/versions': typeof AuthedProjectsProjectIdContentContentIdVersionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/profile': typeof AuthedProfileRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/projects/$projectId/brand-voices': typeof AuthedProjectsProjectIdBrandVoicesRoute
  '/projects/$projectId/categories': typeof AuthedProjectsProjectIdCategoriesRoute
  '/projects/$projectId/examples': typeof AuthedProjectsProjectIdExamplesRoute
  '/projects/$projectId/knowledge-base': typeof AuthedProjectsProjectIdKnowledgeBaseRoute
  '/projects/$projectId/personas': typeof AuthedProjectsProjectIdPersonasRoute
  '/projects/$projectId/settings': typeof AuthedProjectsProjectIdSettingsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/projects/$projectId/content/$contentId': typeof AuthedProjectsProjectIdContentContentIdRouteWithChildren
  '/projects/$projectId/content/new': typeof AuthedProjectsProjectIdContentNewRoute
  '/projects/$projectId/content': typeof AuthedProjectsProjectIdContentIndexRoute
  '/projects/$projectId/content/$contentId/images': typeof AuthedProjectsProjectIdContentContentIdImagesRoute
  '/projects/$projectId/content/$contentId/versions': typeof AuthedProjectsProjectIdContentContentIdVersionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/projects/$projectId': typeof AuthedProjectsProjectIdRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/_authed/projects/$projectId/brand-voices': typeof AuthedProjectsProjectIdBrandVoicesRoute
  '/_authed/projects/$projectId/categories': typeof AuthedProjectsProjectIdCategoriesRoute
  '/_authed/projects/$projectId/examples': typeof AuthedProjectsProjectIdExamplesRoute
  '/_authed/projects/$projectId/knowledge-base': typeof AuthedProjectsProjectIdKnowledgeBaseRoute
  '/_authed/projects/$projectId/personas': typeof AuthedProjectsProjectIdPersonasRoute
  '/_authed/projects/$projectId/settings': typeof AuthedProjectsProjectIdSettingsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/_authed/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/_authed/projects/$projectId/content/$contentId': typeof AuthedProjectsProjectIdContentContentIdRouteWithChildren
  '/_authed/projects/$projectId/content/new': typeof AuthedProjectsProjectIdContentNewRoute
  '/_authed/projects/$projectId/content/': typeof AuthedProjectsProjectIdContentIndexRoute
  '/_authed/projects/$projectId/content/$contentId/images': typeof AuthedProjectsProjectIdContentContentIdImagesRoute
  '/_authed/projects/$projectId/content/$contentId/versions': typeof AuthedProjectsProjectIdContentContentIdVersionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/onboarding'
    | '/profile'
    | '/projects/$projectId'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/projects/$projectId/brand-voices'
    | '/projects/$projectId/categories'
    | '/projects/$projectId/examples'
    | '/projects/$projectId/knowledge-base'
    | '/projects/$projectId/personas'
    | '/projects/$projectId/settings'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/projects/$projectId/'
    | '/demo/start/ssr'
    | '/projects/$projectId/content/$contentId'
    | '/projects/$projectId/content/new'
    | '/projects/$projectId/content'
    | '/projects/$projectId/content/$contentId/images'
    | '/projects/$projectId/content/$contentId/versions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/onboarding'
    | '/profile'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/projects/$projectId/brand-voices'
    | '/projects/$projectId/categories'
    | '/projects/$projectId/examples'
    | '/projects/$projectId/knowledge-base'
    | '/projects/$projectId/personas'
    | '/projects/$projectId/settings'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/projects/$projectId'
    | '/demo/start/ssr'
    | '/projects/$projectId/content/$contentId'
    | '/projects/$projectId/content/new'
    | '/projects/$projectId/content'
    | '/projects/$projectId/content/$contentId/images'
    | '/projects/$projectId/content/$contentId/versions'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/dashboard'
    | '/_authed/onboarding'
    | '/_authed/profile'
    | '/_authed/projects/$projectId'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/_authed/projects/$projectId/brand-voices'
    | '/_authed/projects/$projectId/categories'
    | '/_authed/projects/$projectId/examples'
    | '/_authed/projects/$projectId/knowledge-base'
    | '/_authed/projects/$projectId/personas'
    | '/_authed/projects/$projectId/settings'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/_authed/projects/$projectId/'
    | '/demo/start/ssr/'
    | '/_authed/projects/$projectId/content/$contentId'
    | '/_authed/projects/$projectId/content/new'
    | '/_authed/projects/$projectId/content/'
    | '/_authed/projects/$projectId/content/$contentId/images'
    | '/_authed/projects/$projectId/content/$contentId/versions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/projects/$projectId': {
      id: '/_authed/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthedProjectsProjectIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/projects/$projectId/': {
      id: '/_authed/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/projects/$projectId/settings': {
      id: '/_authed/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AuthedProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/personas': {
      id: '/_authed/projects/$projectId/personas'
      path: '/personas'
      fullPath: '/projects/$projectId/personas'
      preLoaderRoute: typeof AuthedProjectsProjectIdPersonasRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/knowledge-base': {
      id: '/_authed/projects/$projectId/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/projects/$projectId/knowledge-base'
      preLoaderRoute: typeof AuthedProjectsProjectIdKnowledgeBaseRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/examples': {
      id: '/_authed/projects/$projectId/examples'
      path: '/examples'
      fullPath: '/projects/$projectId/examples'
      preLoaderRoute: typeof AuthedProjectsProjectIdExamplesRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/categories': {
      id: '/_authed/projects/$projectId/categories'
      path: '/categories'
      fullPath: '/projects/$projectId/categories'
      preLoaderRoute: typeof AuthedProjectsProjectIdCategoriesRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/brand-voices': {
      id: '/_authed/projects/$projectId/brand-voices'
      path: '/brand-voices'
      fullPath: '/projects/$projectId/brand-voices'
      preLoaderRoute: typeof AuthedProjectsProjectIdBrandVoicesRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/content/': {
      id: '/_authed/projects/$projectId/content/'
      path: '/content'
      fullPath: '/projects/$projectId/content'
      preLoaderRoute: typeof AuthedProjectsProjectIdContentIndexRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/content/new': {
      id: '/_authed/projects/$projectId/content/new'
      path: '/content/new'
      fullPath: '/projects/$projectId/content/new'
      preLoaderRoute: typeof AuthedProjectsProjectIdContentNewRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/content/$contentId': {
      id: '/_authed/projects/$projectId/content/$contentId'
      path: '/content/$contentId'
      fullPath: '/projects/$projectId/content/$contentId'
      preLoaderRoute: typeof AuthedProjectsProjectIdContentContentIdRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/content/$contentId/versions': {
      id: '/_authed/projects/$projectId/content/$contentId/versions'
      path: '/versions'
      fullPath: '/projects/$projectId/content/$contentId/versions'
      preLoaderRoute: typeof AuthedProjectsProjectIdContentContentIdVersionsRouteImport
      parentRoute: typeof AuthedProjectsProjectIdContentContentIdRoute
    }
    '/_authed/projects/$projectId/content/$contentId/images': {
      id: '/_authed/projects/$projectId/content/$contentId/images'
      path: '/images'
      fullPath: '/projects/$projectId/content/$contentId/images'
      preLoaderRoute: typeof AuthedProjectsProjectIdContentContentIdImagesRouteImport
      parentRoute: typeof AuthedProjectsProjectIdContentContentIdRoute
    }
  }
}

interface AuthedProjectsProjectIdContentContentIdRouteChildren {
  AuthedProjectsProjectIdContentContentIdImagesRoute: typeof AuthedProjectsProjectIdContentContentIdImagesRoute
  AuthedProjectsProjectIdContentContentIdVersionsRoute: typeof AuthedProjectsProjectIdContentContentIdVersionsRoute
}

const AuthedProjectsProjectIdContentContentIdRouteChildren: AuthedProjectsProjectIdContentContentIdRouteChildren =
  {
    AuthedProjectsProjectIdContentContentIdImagesRoute:
      AuthedProjectsProjectIdContentContentIdImagesRoute,
    AuthedProjectsProjectIdContentContentIdVersionsRoute:
      AuthedProjectsProjectIdContentContentIdVersionsRoute,
  }

const AuthedProjectsProjectIdContentContentIdRouteWithChildren =
  AuthedProjectsProjectIdContentContentIdRoute._addFileChildren(
    AuthedProjectsProjectIdContentContentIdRouteChildren,
  )

interface AuthedProjectsProjectIdRouteChildren {
  AuthedProjectsProjectIdBrandVoicesRoute: typeof AuthedProjectsProjectIdBrandVoicesRoute
  AuthedProjectsProjectIdCategoriesRoute: typeof AuthedProjectsProjectIdCategoriesRoute
  AuthedProjectsProjectIdExamplesRoute: typeof AuthedProjectsProjectIdExamplesRoute
  AuthedProjectsProjectIdKnowledgeBaseRoute: typeof AuthedProjectsProjectIdKnowledgeBaseRoute
  AuthedProjectsProjectIdPersonasRoute: typeof AuthedProjectsProjectIdPersonasRoute
  AuthedProjectsProjectIdSettingsRoute: typeof AuthedProjectsProjectIdSettingsRoute
  AuthedProjectsProjectIdIndexRoute: typeof AuthedProjectsProjectIdIndexRoute
  AuthedProjectsProjectIdContentContentIdRoute: typeof AuthedProjectsProjectIdContentContentIdRouteWithChildren
  AuthedProjectsProjectIdContentNewRoute: typeof AuthedProjectsProjectIdContentNewRoute
  AuthedProjectsProjectIdContentIndexRoute: typeof AuthedProjectsProjectIdContentIndexRoute
}

const AuthedProjectsProjectIdRouteChildren: AuthedProjectsProjectIdRouteChildren =
  {
    AuthedProjectsProjectIdBrandVoicesRoute:
      AuthedProjectsProjectIdBrandVoicesRoute,
    AuthedProjectsProjectIdCategoriesRoute:
      AuthedProjectsProjectIdCategoriesRoute,
    AuthedProjectsProjectIdExamplesRoute: AuthedProjectsProjectIdExamplesRoute,
    AuthedProjectsProjectIdKnowledgeBaseRoute:
      AuthedProjectsProjectIdKnowledgeBaseRoute,
    AuthedProjectsProjectIdPersonasRoute: AuthedProjectsProjectIdPersonasRoute,
    AuthedProjectsProjectIdSettingsRoute: AuthedProjectsProjectIdSettingsRoute,
    AuthedProjectsProjectIdIndexRoute: AuthedProjectsProjectIdIndexRoute,
    AuthedProjectsProjectIdContentContentIdRoute:
      AuthedProjectsProjectIdContentContentIdRouteWithChildren,
    AuthedProjectsProjectIdContentNewRoute:
      AuthedProjectsProjectIdContentNewRoute,
    AuthedProjectsProjectIdContentIndexRoute:
      AuthedProjectsProjectIdContentIndexRoute,
  }

const AuthedProjectsProjectIdRouteWithChildren =
  AuthedProjectsProjectIdRoute._addFileChildren(
    AuthedProjectsProjectIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedProjectsProjectIdRoute: typeof AuthedProjectsProjectIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedProjectsProjectIdRoute: AuthedProjectsProjectIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
